name: Linux manylinux Wheels

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-manylinux:
    runs-on: ubuntu-latest
    env:
      CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
      CIBW_SKIP: "pp* *-musllinux*"
      CIBW_ARCHS_LINUX: "x86_64"
      CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
      CIBW_ENVIRONMENT: >
        QT_PREFIX_PATH=/opt/Qt/6.5.3/gcc_64
        PATH=/opt/Qt/6.5.3/gcc_64/bin:$PATH
        LD_LIBRARY_PATH=/opt/Qt/6.5.3/gcc_64/lib:$LD_LIBRARY_PATH
      CIBW_BEFORE_ALL_LINUX: "bash ci/install_qt_linux.sh"
      CIBW_BEFORE_BUILD: "bash ci/build_cpp_and_install.sh"
      CIBW_BUILD_VERBOSITY: "1"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-manylinux
          path: wheelhouse/*.whl
